cd: 10
localNum: 50
isDownload: false
isTellMaster: false
isAllowSearchLocalImg: false
prohibitedUserList: []
apMaster: []
gp:
  global:
    enable: true
    JH: true
    gcd: 20
    pcd: 40
    isRecall: false
    recallDelay: 60
    isBan: false
    usageLimit: 30
  private:
    enable: false
